name: py3
channels:
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'jupyter_contrib_core=0.3.0=py35_0'
- !!python/unicode
  'jupyter_contrib_nbextensions=0.2.1=py35_0'
- !!python/unicode
  'jupyter_nbextensions_configurator=0.2.2=py35_0'
- !!python/unicode
  '_nb_ext_conf=0.3.0=py35_0'
- !!python/unicode
  'accelerate=2.3.1=np111py35_0'
- !!python/unicode
  'accelerate_cudalib=2.0=0'
- !!python/unicode
  'anaconda-client=1.6.3=py35_0'
- !!python/unicode
  'bleach=1.5.0=py35_0'
- !!python/unicode
  'bokeh=0.12.4=py35_0'
- !!python/unicode
  'cffi=1.9.1=py35_0'
- !!python/unicode
  'chest=0.2.3=py35_0'
- !!python/unicode
  'cloudpickle=0.2.2=py35_0'
- !!python/unicode
  'clyent=1.2.2=py35_0'
- !!python/unicode
  'cudatoolkit=7.5=0'
- !!python/unicode
  'cycler=0.10.0=py35_0'
- !!python/unicode
  'cython=0.25.2=py35_0'
- !!python/unicode
  'dask=0.14.1=py35_0'
- !!python/unicode
  'dbus=1.10.10=0'
- !!python/unicode
  'decorator=4.0.11=py35_0'
- !!python/unicode
  'entrypoints=0.2.2=py35_1'
- !!python/unicode
  'expat=2.1.0=0'
- !!python/unicode
  'fontconfig=2.12.1=3'
- !!python/unicode
  'freetype=2.5.5=2'
- !!python/unicode
  'glib=2.50.2=1'
- !!python/unicode
  'gst-plugins-base=1.8.0=0'
- !!python/unicode
  'gstreamer=1.8.0=0'
- !!python/unicode
  'hdf5=1.8.17=1'
- !!python/unicode
  'heapdict=1.0.0=py35_1'
- !!python/unicode
  'html5lib=0.999=py35_0'
- !!python/unicode
  'icu=54.1=0'
- !!python/unicode
  'ipykernel=4.6.1=py35_0'
- !!python/unicode
  'ipython=6.0.0=py35_0'
- !!python/unicode
  'ipython_genutils=0.2.0=py35_0'
- !!python/unicode
  'ipywidgets=6.0.0=py35_0'
- !!python/unicode
  'jinja2=2.9.6=py35_0'
- !!python/unicode
  'jpeg=9b=0'
- !!python/unicode
  'jsonschema=2.6.0=py35_0'
- !!python/unicode
  'jupyter=1.0.0=py35_3'
- !!python/unicode
  'jupyter_client=5.0.1=py35_0'
- !!python/unicode
  'jupyter_console=5.1.0=py35_0'
- !!python/unicode
  'jupyter_core=4.3.0=py35_0'
- !!python/unicode
  'libffi=3.2.1=1'
- !!python/unicode
  'libgcc=5.2.0=0'
- !!python/unicode
  'libgfortran=3.0.0=1'
- !!python/unicode
  'libgpuarray=0.6.4=0'
- !!python/unicode
  'libiconv=1.14=0'
- !!python/unicode
  'libpng=1.6.27=0'
- !!python/unicode
  'libsodium=1.0.10=0'
- !!python/unicode
  'libxcb=1.12=1'
- !!python/unicode
  'libxml2=2.9.4=0'
- !!python/unicode
  'line_profiler=2.0=py35_0'
- !!python/unicode
  'llvm=3.3=0'
- !!python/unicode
  'llvmlite=0.15.0=py35_0'
- !!python/unicode
  'locket=0.2.0=py35_1'
- !!python/unicode
  'mako=1.0.6=py35_0'
- !!python/unicode
  'markupsafe=0.23=py35_2'
- !!python/unicode
  'matplotlib=2.0.0=np111py35_0'
- !!python/unicode
  'mesa=10.5.4=0'
- !!python/unicode
  'mistune=0.7.4=py35_0'
- !!python/unicode
  'mkl=11.3.3=0'
- !!python/unicode
  'mkl-service=1.1.2=py35_3'
- !!python/unicode
  'mpmath=0.19=py35_1'
- !!python/unicode
  'nb_anacondacloud=1.2.0=py35_0'
- !!python/unicode
  'nb_conda=2.0.0=py35_0'
- !!python/unicode
  'nb_conda_kernels=2.0.0=py35_0'
- !!python/unicode
  'nbconvert=5.1.1=py35_0'
- !!python/unicode
  'nbformat=4.3.0=py35_0'
- !!python/unicode
  'nbpresent=3.0.2=py35_0'
- !!python/unicode
  'nose=1.3.7=py35_1'
- !!python/unicode
  'notebook=5.0.0=py35_0'
- !!python/unicode
  'numba=0.30.1=np111py35_0'
- !!python/unicode
  'numexpr=2.6.1=np111py35_1'
- !!python/unicode
  'numpy=1.11.2=py35_0'
- !!python/unicode
  'openssl=1.0.2k=1'
- !!python/unicode
  'pandas=0.19.2=np111py35_1'
- !!python/unicode
  'pandocfilters=1.4.1=py35_0'
- !!python/unicode
  'partd=0.3.7=py35_0'
- !!python/unicode
  'path.py=10.3.1=py35_0'
- !!python/unicode
  'patsy=0.4.1=py35_0'
- !!python/unicode
  'pcre=8.39=1'
- !!python/unicode
  'pexpect=4.2.1=py35_0'
- !!python/unicode
  'pickleshare=0.7.4=py35_0'
- !!python/unicode
  'pip=9.0.1=py35_1'
- !!python/unicode
  'prompt_toolkit=1.0.14=py35_0'
- !!python/unicode
  'psutil=5.2.2=py35_0'
- !!python/unicode
  'ptyprocess=0.5.1=py35_0'
- !!python/unicode
  'pycparser=2.17=py35_0'
- !!python/unicode
  'pygments=2.2.0=py35_0'
- !!python/unicode
  'pygpu=0.6.4=py35_0'
- !!python/unicode
  'pyparsing=2.1.4=py35_0'
- !!python/unicode
  'pyqt=5.6.0=py35_2'
- !!python/unicode
  'pytables=3.3.0=np111py35_0'
- !!python/unicode
  'python=3.5.2=0'
- !!python/unicode
  'python-dateutil=2.6.0=py35_0'
- !!python/unicode
  'pytz=2017.2=py35_0'
- !!python/unicode
  'pyyaml=3.12=py35_0'
- !!python/unicode
  'pyzmq=16.0.2=py35_0'
- !!python/unicode
  'qt=5.6.2=3'
- !!python/unicode
  'qtconsole=4.3.0=py35_0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'requests=2.13.0=py35_0'
- !!python/unicode
  'scipy=0.18.1=np111py35_0'
- !!python/unicode
  'seaborn=0.7.1=py35_0'
- !!python/unicode
  'setuptools=27.2.0=py35_0'
- !!python/unicode
  'simplegeneric=0.8.1=py35_1'
- !!python/unicode
  'sip=4.18=py35_0'
- !!python/unicode
  'six=1.10.0=py35_0'
- !!python/unicode
  'snakeviz=0.4.1=py35_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'statsmodels=0.8.0=np111py35_0'
- !!python/unicode
  'sympy=1.0=py35_0'
- !!python/unicode
  'system=5.8=2'
- !!python/unicode
  'terminado=0.6=py35_0'
- !!python/unicode
  'testpath=0.3=py35_0'
- !!python/unicode
  'theano=0.9.0=py35_0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'toolz=0.8.2=py35_0'
- !!python/unicode
  'tornado=4.5.1=py35_0'
- !!python/unicode
  'traitlets=4.3.2=py35_0'
- !!python/unicode
  'wcwidth=0.1.7=py35_0'
- !!python/unicode
  'wget=2.2=py35_0'
- !!python/unicode
  'wheel=0.29.0=py35_0'
- !!python/unicode
  'widgetsnbextension=2.0.0=py35_0'
- !!python/unicode
  'xlrd=1.0.0=py35_0'
- !!python/unicode
  'xz=5.2.2=1'
- !!python/unicode
  'yaml=0.1.6=0'
- !!python/unicode
  'zeromq=4.1.5=0'
- !!python/unicode
  'zlib=1.2.8=3'
- pip:
  - alabaster==0.7.10
  - algopy==0.5.3
  - babel==2.4.0
  - bibtexparser==0.6.2
  - commonmark==0.5.4
  - docutils==0.13.1
  - h5py==2.7.0
  - imagesize==0.7.1
  - iminuit==1.2
  - ipycache==0.1.5.dev0
  - ipython-genutils==0.2.0
  - joblib==0.11
  - jupyter-core==4.3.0
  - line-profiler==2.0
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - nbsphinx==0.2.13
  - numdifftools==0.9.20
  - numpydoc==0.6.0
  - peakutils==1.0.3
  - prompt-toolkit==1.0.14
  - pymc3==3.1rc3
  - recommonmark==0.4.0
  - snowballstemmer==1.2.1
  - sphinx==1.5.5
  - tables==3.3.0
  - tqdm==4.10.0
  - yapf==0.16.1

